import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Navbar } from '../components/Navbar';
import { Projects } from '../components/Projects';
import { Theme } from '../components/Theme';
import { Timer } from '../components/Timer';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Open Source Sunday</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar hasSubmitted={false} />
      <div className={styles.fill} />
      <Timer />
      <Theme />
      <Projects />
      {/* <main className={styles.main}></main> */}
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
